language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
    - php: hhvm
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: hhvm
    - php: 7.1
  fast_finish: true

addons:
  apt:
    packages:
    - libssh2-1-dev
    - libssh2-php

before_script:
  - composer self-update
  - composer install --dev --ignore-platform-reqs
#after_script:
#  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script:
  - bin/phpspec run --format=pretty
  - bin/php-cs-fixer fix --dry-run
