language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

addons:
  apt:
    packages:
    - libssh2-1-dev
    - libssh2-php

before_script:
  - composer self-update
  - composer install --dev --ignore-platform-reqs
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then echo "extensions: [PhpSpec\Extension\CodeCoverageExtension]" >> phpspec.yml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then wget https://github.com/digitalkaoz/typehint-to-docblock/releases/download/0.2.2/typehint-to-docblock.phar && php typehint-to-docblock.phar transform spec; fi;'

after_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

script:
  - bin/phpspec run --format=pretty
