language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

addons:
  apt:
    packages:
    - libssh2-1-dev
    - php5-ssh2

before_script:
  - php -m | grep ssh2
  - composer self-update
  - composer install --dev

script:
  - bin/phpspec run --format=pretty
