language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: 7.0
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

before_script:
  - composer self-update

install:
  - composer install

script:
   - bin/phpspec run --format=pretty
